import { test, expect } from '@playwright/test';

test('test', async ({ page, context }) => {
  // Recording...
  await page.goto('http://127.0.0.1:8080/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByLabel('Username or email').fill('dennis');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'New Game' }).click();
  const page1 = await context.newPage();
  await page1.goto('http://127.0.0.1:8080/');
  await page1.getByRole('link', { name: 'Logout' }).click();
  await page1.getByRole('link', { name: 'Login' }).click();
  await page1.locator('#reset-login').click();
  await page1.getByLabel('Username or email').click();
  await page1.getByLabel('Username or email').fill('alice');
  await page1.getByLabel('Password').click();
  await page1.getByLabel('Password').fill('1234');
  await page1.getByRole('button', { name: 'Sign In' }).click();
  const page2 = await context.newPage();
  await page2.goto('http://127.0.0.1:8080/');
  await page2.getByRole('link', { name: 'Logout' }).click();
  await page2.getByRole('link', { name: 'Login' }).click();
  await page2.locator('#reset-login').click();
  await page2.getByLabel('Username or email').click();
  await page2.getByLabel('Username or email').fill('kevin');
  await page2.getByLabel('Password').click();
  await page2.getByLabel('Password').fill('1234');
  await page2.getByRole('button', { name: 'Sign In' }).click();
  const page3 = await context.newPage();
  await page3.goto('http://127.0.0.1:8080/');
  await page3.getByRole('link', { name: 'Logout' }).click();
  await page3.getByRole('link', { name: 'Login' }).click();
  await page3.locator('#reset-login').click();
  await page3.getByLabel('Username or email').click();
  await page3.getByLabel('Username or email').fill('kate');
  await page3.getByLabel('Password').click();
  await page3.getByLabel('Password').fill('1234');
  await page3.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('button', { name: 'Draw Card' }).click();
  await page1.getByRole('button', { name: 'Draw Card' }).click();
  await page2.getByRole('button', { name: 'Draw Card' }).click();
  await page3.getByRole('button', { name: 'Draw Card' }).click();
  await page.locator('div:nth-child(8) > .grid-container > .card > .card-body > .btn').click();
  await page1.getByRole('button', { name: 'Draw Card' }).click();
  await page1.locator('div:nth-child(7) > .grid-container > .card > .card-body > .btn').click();
  await page.getByRole('button', { name: 'Pong' }).click();
  await page.locator('div:nth-child(8) > .grid-container > .card > .card-body > .btn').click();
  await page1.getByRole('button', { name: 'Ok.' }).click();
  await page1.getByRole('button', { name: 'Draw Card' }).click();
  await page1.locator('div:nth-child(14) > .grid-container > .card > .card-body > .btn').click();
  await page2.getByRole('button', { name: 'Chow' }).click();
  await page2.getByRole('button', { name: '2bamboo-3bamboo-4bamboo-' }).click();
  await page2.locator('div:nth-child(9) > .grid-container > .card > .card-body > .btn').click();
  await page3.getByRole('button', { name: 'Kong' }).click();
  await page3.getByRole('button', { name: 'Draw Card' }).click();
  await page3.locator('div:nth-child(4) > .grid-container > .card > .card-body > .btn').first().click();
  await page3.getByText('Close').click();
  // await page2.locator('div:nth-child(9) > .grid-container > .card > .card-body > .btn').click();
  // await page3.getByRole('button', { name: 'Kong' }).click();
  // await page3.getByRole('button', { name: 'Draw Card' }).click();
  // await page3.locator('div:nth-child(4) > .grid-container > .card > .card-body > .btn').first().click();
  // await page3.getByText('Close').click();
});