# vite build
FROM library/node:16-alpine as node
WORKDIR /home/node/app
RUN mkdir server
WORKDIR /home/node/app/server
COPY server/*.json ./
COPY server/model.ts ./
RUN npm i

WORKDIR /home/node/app
RUN mkdir ui
COPY ui/*.js* ./ui/
COPY ui/.npmrc ./ui/
COPY ui/index.html ./ui/
COPY ui/src ./ui/src
WORKDIR /home/node/app/ui
RUN npm i
RUN ls -al && npm run build

# nginx
FROM library/nginx:1
COPY --from=node /home/node/app/ui/dist /usr/share/nginx/html
COPY ui/nginx.conf /etc/nginx/nginx.conf